// Convert snarkjs vkey.json -> a Rust source file with a groth16-solana
// Groth16Verifyingkey constant. groth16-solana expects big-endian 32-byte limbs;
// G2 element ordering (c1,c0) matches Light Protocol's convention.
import fs from "node:fs";

// args (cwd-relative): [vkeyJson] [outRs] [constName]; defaults = seal gate vk.
const VKEY = process.argv[2] || "circuits/vkey.json";
const OUT = process.argv[3] || "program/programs/seal/src/vk.rs";
const CONST = process.argv[4] || "VERIFYINGKEY";

const vk = JSON.parse(fs.readFileSync(VKEY));

// field element (decimal string) -> 32 big-endian bytes
function toBytes(dec) {
  let h = BigInt(dec).toString(16).padStart(64, "0");
  const out = [];
  for (let i = 0; i < 64; i += 2) out.push(parseInt(h.slice(i, i + 2), 16));
  return out;
}
const g1 = (p) => [...toBytes(p[0]), ...toBytes(p[1])];
// G2: snarkjs stores [[x0,x1],[y0,y1]]; Light expects [x1,x0,y1,y0]
const g2 = (p) => [...toBytes(p[0][1]), ...toBytes(p[0][0]), ...toBytes(p[1][1]), ...toBytes(p[1][0])];

const arr = (bytes) => `[${bytes.join(",")}]`;
const ic = vk.IC.map(g1);
const nPublic = vk.nPublic;

const src = `// AUTO-GENERATED by scripts/vk_to_rust.mjs from ${VKEY}. Do not edit.
use groth16_solana::groth16::Groth16Verifyingkey;

pub const ${CONST}: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${nPublic},
    vk_alpha_g1: ${arr(g1(vk.vk_alpha_1))},
    vk_beta_g2: ${arr(g2(vk.vk_beta_2))},
    vk_gamme_g2: ${arr(g2(vk.vk_gamme_2 ?? vk.vk_gamma_2))},
    vk_delta_g2: ${arr(g2(vk.vk_delta_2))},
    vk_ic: &[
${ic.map((x) => "        " + arr(x)).join(",\n")}
    ],
};
`;
fs.writeFileSync(OUT, src);
console.log(`wrote ${OUT} (const ${CONST}, nPublic=${nPublic}, IC len=${ic.length})`);
